project:
  type: website

website:
  title: "ISSS624 - Applied Geospatial Analytics"
  navbar:
    background: "#9eb5f7"
    search: true
    left: 
      - text: Hands-on Exercise
        menu: 
        - text: Hands-on Exercise 1
          href: Hands-on_Exercise/Hands-on_Ex1/Hands-on_Ex1.html
        - text: Hands-on Exercise 2
          href: Hands-on_Exercise/Hands-on_Ex2/Hands-on_Ex2.html
        - text: Hands-on Exercise 3
          href: Hands-on_Exercise/Hands-on_Ex3/Hands-on_Ex3.html
        - text: Hands-on Exercise 4
          href: Hands-on_Exercise/Hands-on_Ex4/Hands-on_Ex4.html
        - text: Hands-on Exercise 5
        - text: Hands-on Exercise 6
        - text: Hands-on Exercise 7
        - text: Hands-on Exercise 8
          href: Hands-on_Exercise/Hands-on_Ex8/Hands-on_Ex8.html
        - text: Hands-on Exercise 9
          href: Hands-on_Exercise/Hands-on_Ex9/Hands-on_Ex9.html
        - text: Hands-on Exercise 10
          href: Hands-on_Exercise/Hands-on_Ex10/Hands-on_Ex10.html
        - text: Hands-on Exercise 15
          href: Hands-on_Exercise/Hands-on_Ex15/Hands-on_Ex15.html
      - text: In-class Exercise
        menu: 
        - text: In-class Exercise 1
          href: In-class_Exercise/In-class_Ex1/In-class_Ex1.html
        - text: In-class Exercise 2
          href: In-class_Exercise/In-class_Ex2/In-class_Ex2.html
        - text: In-class Exercise 3
          href: In-class_Exercise/In-class_Ex3/In-class_Ex3.html
        - text: In-class Exercise 4
          href: In-class_Exercise/In-class_Ex4/In-class_Ex4.html
        - text: In-class Exercise 5
      - text: Take-home Exercise
        menu: 
        - text: Take-home Exercise 1
          href: Take-home_Exercise/Take-home_Ex1/Take-home_Ex1.html
        - text: Take-home Exercise 2
          href: Take-home_Exercise/Take-home_Ex2/Take-home_Ex2.html
        
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Table of Contents"
    number-sections: true

editor: visual

